# Generated by Django 4.1.5 on 2023-02-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sta_infos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='access',
        ),
    ]
