# Generated by Django 4.1.5 on 2023-02-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sta_infos', '0002_remove_stadium_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='team',
            new_name='club',
        ),
        migrations.AddField(
            model_name='stadium',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
