# Generated by Django 4.1.5 on 2023-02-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sta_infos', '0004_topic_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='stadium',
        ),
        migrations.AddField(
            model_name='review',
            name='stadium',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sta_infos.stadium'),
        ),
        migrations.AddField(
            model_name='review',
            name='topics',
            field=models.ManyToManyField(to='sta_infos.topic'),
        ),
    ]
