# Generated by Django 4.1.5 on 2023-02-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sta_infos', '0010_review_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='website',
        ),
    ]
